services:
  - type: web
    name: vectorpayoff-app
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free